name: bundle
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: 0.52.0
      - name: Test Policies
        run: opa test .
      - name: Build OPA Bundle
        id: build_opa_bundle
        run: opa build --ignore "*_test.rego" policy
      - name: Release OPA Bundle
        run: gh release create ${GITHUB_SHA} bundle.tar.gz
        env:
          GH_TOKEN: ${{ github.token }}